name: Deploy Docker Image to VPS

on:
  push:
    branches:
      - main  # or whichever branch you want to trigger deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

    - name: Build Docker image
      run: |
        echo "${{ secrets.SUPABASE_KEY }}" > supabase_key.txt
        echo "${{ secrets.SUPABASE_URL }}" > supabase_url.txt
        docker build \
        --secret id=supabase_key,src=supabase_key.txt \
        --secret id=supabase_url,src=supabase_url.txt \
        -t qr-restaurants:latest .

    - name: Save Docker image
      run: |
        docker save qr-restaurants:latest | gzip > qr-restaurants.tar.gz

    - name: Copy image to VPS
      run: |
        scp qr-restaurants.tar.gz ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/tmp/qr-restaurants.tar.gz

    - name: Load and run Docker image on VPS
      run: |
        ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
          docker load < /tmp/qr-restaurants.tar.gz
          cd docker
          docker compose down qr-restaurants-app || true
          docker compose up -d qr-restaurants-app || true
        EOF